/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Achievement {
    id: string;
    unlockedAt: Time;
}
export type Time = bigint;
export interface DailyChallenge {
    completedAt?: Time;
    targetScore: bigint;
    date: string;
    completed: boolean;
}
export interface PlayerStats {
    lastPlayed: Time;
    totalGamesPlayed: bigint;
    highScore: bigint;
    totalBlocksPlaced: bigint;
    totalLinesCleared: bigint;
}
export interface GameScore {
    principal: Principal;
    score: bigint;
    timestamp: Time;
}
export interface backendInterface {
    /**
     * / Complete today's daily challenge
     */
    completeDailyChallenge(): Promise<boolean>;
    /**
     * / Get player's achievements
     */
    getAchievements(): Promise<Array<Achievement>>;
    /**
     * / Get today's daily challenge for the player
     */
    getDailyChallenge(): Promise<DailyChallenge | null>;
    /**
     * / Get the player's high score
     */
    getHighScore(): Promise<bigint>;
    /**
     * / Get player's rank on the leaderboard (1-indexed, 0 if not on board)
     */
    getPlayerRank(): Promise<bigint>;
    /**
     * / Get the current player's stats
     */
    getPlayerStats(): Promise<PlayerStats>;
    /**
     * / Get top scores from the global leaderboard
     */
    getTopScores(limit: bigint): Promise<Array<GameScore>>;
    /**
     * / Get the current player's username (returns null if not registered)
     */
    getUsername(): Promise<string | null>;
    /**
     * / Get username for any principal (for leaderboard display)
     */
    getUsernameByPrincipal(principal: Principal): Promise<string | null>;
    /**
     * / Returns a greeting message
     */
    greet(name: string): Promise<string>;
    /**
     * / Health check function
     */
    health(): Promise<boolean>;
    /**
     * / Set today's daily challenge (called when loading game)
     */
    initDailyChallenge(date: string, targetScore: bigint): Promise<DailyChallenge>;
    /**
     * / Check if a username is already taken
     */
    isUsernameTaken(username: string): Promise<boolean>;
    /**
     * / Register a username for the current player
     */
    registerUsername(username: string): Promise<boolean>;
    /**
     * / Submit a new score to the leaderboard
     */
    submitScore(score: bigint): Promise<void>;
    /**
     * / Unlock an achievement for the player
     */
    unlockAchievement(achievementId: string): Promise<boolean>;
    /**
     * / Update player stats after a game
     */
    updateStats(linesCleared: bigint, blocksPlaced: bigint, score: bigint): Promise<PlayerStats>;
    /**
     * / Returns the caller's principal
     */
    whoami(): Promise<Principal>;
}
import type { DailyChallenge as _DailyChallenge, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeDailyChallenge(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeDailyChallenge();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeDailyChallenge();
            return result;
        }
    }
    async getAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements();
            return result;
        }
    }
    async getDailyChallenge(): Promise<DailyChallenge | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyChallenge();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyChallenge();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHighScore(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getHighScore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHighScore();
            return result;
        }
    }
    async getPlayerRank(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerRank();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerRank();
            return result;
        }
    }
    async getPlayerStats(): Promise<PlayerStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerStats();
            return result;
        }
    }
    async getTopScores(arg0: bigint): Promise<Array<GameScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopScores(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopScores(arg0);
            return result;
        }
    }
    async getUsername(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsername();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsername();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsernameByPrincipal(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsernameByPrincipal(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsernameByPrincipal(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async greet(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.greet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.greet(arg0);
            return result;
        }
    }
    async health(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.health();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.health();
            return result;
        }
    }
    async initDailyChallenge(arg0: string, arg1: bigint): Promise<DailyChallenge> {
        if (this.processError) {
            try {
                const result = await this.actor.initDailyChallenge(arg0, arg1);
                return from_candid_DailyChallenge_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initDailyChallenge(arg0, arg1);
            return from_candid_DailyChallenge_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async isUsernameTaken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameTaken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameTaken(arg0);
            return result;
        }
    }
    async registerUsername(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUsername(arg0);
            return result;
        }
    }
    async submitScore(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitScore(arg0);
            return result;
        }
    }
    async unlockAchievement(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockAchievement(arg0);
            return result;
        }
    }
    async updateStats(arg0: bigint, arg1: bigint, arg2: bigint): Promise<PlayerStats> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStats(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStats(arg0, arg1, arg2);
            return result;
        }
    }
    async whoami(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.whoami();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.whoami();
            return result;
        }
    }
}
function from_candid_DailyChallenge_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyChallenge): DailyChallenge {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyChallenge]): DailyChallenge | null {
    return value.length === 0 ? null : from_candid_DailyChallenge_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: [] | [_Time];
    targetScore: bigint;
    date: string;
    completed: boolean;
}): {
    completedAt?: Time;
    targetScore: bigint;
    date: string;
    completed: boolean;
} {
    return {
        completedAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.completedAt)),
        targetScore: value.targetScore,
        date: value.date,
        completed: value.completed
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
