/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Achievement = IDL.Record({ 'id' : IDL.Text, 'unlockedAt' : Time });
export const DailyChallenge = IDL.Record({
  'completedAt' : IDL.Opt(Time),
  'targetScore' : IDL.Nat,
  'date' : IDL.Text,
  'completed' : IDL.Bool,
});
export const PlayerStats = IDL.Record({
  'lastPlayed' : Time,
  'totalGamesPlayed' : IDL.Nat,
  'highScore' : IDL.Nat,
  'totalBlocksPlaced' : IDL.Nat,
  'totalLinesCleared' : IDL.Nat,
});
export const GameScore = IDL.Record({
  'principal' : IDL.Principal,
  'score' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'completeDailyChallenge' : IDL.Func([], [IDL.Bool], []),
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getDailyChallenge' : IDL.Func([], [IDL.Opt(DailyChallenge)], ['query']),
  'getHighScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getPlayerRank' : IDL.Func([], [IDL.Nat], ['query']),
  'getPlayerStats' : IDL.Func([], [PlayerStats], ['query']),
  'getTopScores' : IDL.Func([IDL.Nat], [IDL.Vec(GameScore)], ['query']),
  'getUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUsernameByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'greet' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'health' : IDL.Func([], [IDL.Bool], ['query']),
  'initDailyChallenge' : IDL.Func([IDL.Text, IDL.Nat], [DailyChallenge], []),
  'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'registerUsername' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'submitScore' : IDL.Func([IDL.Nat], [], []),
  'unlockAchievement' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [PlayerStats], []),
  'whoami' : IDL.Func([], [IDL.Principal], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Achievement = IDL.Record({ 'id' : IDL.Text, 'unlockedAt' : Time });
  const DailyChallenge = IDL.Record({
    'completedAt' : IDL.Opt(Time),
    'targetScore' : IDL.Nat,
    'date' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const PlayerStats = IDL.Record({
    'lastPlayed' : Time,
    'totalGamesPlayed' : IDL.Nat,
    'highScore' : IDL.Nat,
    'totalBlocksPlaced' : IDL.Nat,
    'totalLinesCleared' : IDL.Nat,
  });
  const GameScore = IDL.Record({
    'principal' : IDL.Principal,
    'score' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'completeDailyChallenge' : IDL.Func([], [IDL.Bool], []),
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getDailyChallenge' : IDL.Func([], [IDL.Opt(DailyChallenge)], ['query']),
    'getHighScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getPlayerRank' : IDL.Func([], [IDL.Nat], ['query']),
    'getPlayerStats' : IDL.Func([], [PlayerStats], ['query']),
    'getTopScores' : IDL.Func([IDL.Nat], [IDL.Vec(GameScore)], ['query']),
    'getUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUsernameByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'greet' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'health' : IDL.Func([], [IDL.Bool], ['query']),
    'initDailyChallenge' : IDL.Func([IDL.Text, IDL.Nat], [DailyChallenge], []),
    'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'registerUsername' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'submitScore' : IDL.Func([IDL.Nat], [], []),
    'unlockAchievement' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [PlayerStats], []),
    'whoami' : IDL.Func([], [IDL.Principal], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };