/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement { 'id' : string, 'unlockedAt' : Time }
export interface DailyChallenge {
  'completedAt' : [] | [Time],
  'targetScore' : bigint,
  'date' : string,
  'completed' : boolean,
}
export interface GameScore {
  'principal' : Principal,
  'score' : bigint,
  'timestamp' : Time,
}
export interface PlayerStats {
  'lastPlayed' : Time,
  'totalGamesPlayed' : bigint,
  'highScore' : bigint,
  'totalBlocksPlaced' : bigint,
  'totalLinesCleared' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  /**
   * / Complete today's daily challenge
   */
  'completeDailyChallenge' : ActorMethod<[], boolean>,
  /**
   * / Get player's achievements
   */
  'getAchievements' : ActorMethod<[], Array<Achievement>>,
  /**
   * / Get today's daily challenge for the player
   */
  'getDailyChallenge' : ActorMethod<[], [] | [DailyChallenge]>,
  /**
   * / Get the player's high score
   */
  'getHighScore' : ActorMethod<[], bigint>,
  /**
   * / Get player's rank on the leaderboard (1-indexed, 0 if not on board)
   */
  'getPlayerRank' : ActorMethod<[], bigint>,
  /**
   * / Get the current player's stats
   */
  'getPlayerStats' : ActorMethod<[], PlayerStats>,
  /**
   * / Get top scores from the global leaderboard
   */
  'getTopScores' : ActorMethod<[bigint], Array<GameScore>>,
  /**
   * / Get the current player's username (returns null if not registered)
   */
  'getUsername' : ActorMethod<[], [] | [string]>,
  /**
   * / Get username for any principal (for leaderboard display)
   */
  'getUsernameByPrincipal' : ActorMethod<[Principal], [] | [string]>,
  /**
   * / Returns a greeting message
   */
  'greet' : ActorMethod<[string], string>,
  /**
   * / Health check function
   */
  'health' : ActorMethod<[], boolean>,
  /**
   * / Set today's daily challenge (called when loading game)
   */
  'initDailyChallenge' : ActorMethod<[string, bigint], DailyChallenge>,
  /**
   * / Check if a username is already taken
   */
  'isUsernameTaken' : ActorMethod<[string], boolean>,
  /**
   * / Register a username for the current player
   */
  'registerUsername' : ActorMethod<[string], boolean>,
  /**
   * / Submit a new score to the leaderboard
   */
  'submitScore' : ActorMethod<[bigint], undefined>,
  /**
   * / Unlock an achievement for the player
   */
  'unlockAchievement' : ActorMethod<[string], boolean>,
  /**
   * / Update player stats after a game
   */
  'updateStats' : ActorMethod<[bigint, bigint, bigint], PlayerStats>,
  /**
   * / Returns the caller's principal
   */
  'whoami' : ActorMethod<[], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];